// Generated by CoffeeScript 1.6.3
(function() {
  var Config;

  Config = (function() {
    function Config() {}

    Config.prototype.defaultGameState = function(gameState) {
      gameState.turn = 1;
      gameState.players = {};
      return gameState.grave = [];
    };

    return Config;

  })();

  exports.Config = Config;

}).call(this);

/*
//@ sourceMappingURL=config.map
*/
