// Generated by CoffeeScript 1.6.3
(function() {
  var NightManager;

  NightManager = (function() {
    function NightManager() {}

    return NightManager;

  })();

}).call(this);

/*
//@ sourceMappingURL=NightManager.map
*/
