// Generated by CoffeeScript 1.6.3
(function() {
  var Player, bomb, bombInfo, player, players, roleObjects, villager, villagerInfo, _i, _len;

  Player = (function() {
    function Player(playerInfo, roleObjects) {
      this.role = roleObjects[playerInfo.role];
      this.name = playerInfo.name;
      this.roletring = this.role.rolestring;
      this.alive = true;
      this.knowswho = [];
      this.deathinfo = {};
      this.visitstack = [];
    }

    return Player;

  })();

  bomb = {
    'rolestring': 'bomb',
    'die': function(who, how) {
      return log(this);
    }
  };

  villager = {
    'rolestring': 'villager'
  };

  roleObjects = {
    'bomb': bomb,
    'villager': villager
  };

  bombInfo = {
    'name': 'SwaggerBomb',
    'role': 'bomb'
  };

  villagerInfo = {
    'name': 'YoloVillager',
    'role': 'villager'
  };

  players = [];

  players.push(new Player(bombInfo, roleObjects));

  for (_i = 0, _len = players.length; _i < _len; _i++) {
    player = players[_i];
    player.die('village', 'lynch');
  }

}).call(this);

/*
//@ sourceMappingURL=Player.map
*/
