// Generated by CoffeeScript 1.6.3
(function() {
  var Config, GameLobby, QueueManager, uuid;

  GameLobby = require('./GameLobby').GameLobby;

  uuid = require('node-uuid');

  Config = require('./config').Config;

  QueueManager = (function() {
    function QueueManager(io) {
      this.io = io;
      this.gamesArray = [];
      (function(queue) {
        return io.of('/matchmaking').on('connection', function(socket) {
          return queue.beginQueue(socket);
        });
      })(this);
    }

    QueueManager.prototype.beginQueue = function(socket) {
      var game, gameObject, gamefound, newNamespace, queueLength, randomName, removedGame, _results;
      console.log('beginqueue');
      gamefound = false;
      _results = [];
      while (!gamefound) {
        queueLength = this.gamesArray.length;
        if (queueLength !== 0) {
          if (this.gamesArray[queueLength - 1].game.checkStatus()) {
            socket.emit('match_found', this.gamesArray[queueLength - 1].namespace.name);
            gamefound = true;
            _results.push(console.log('found new game'));
          } else {
            removedGame = this.gamesArray.pop().game.outOfQueue();
            _results.push(console.log(removedGame));
          }
        } else {
          console.log('making new game');
          randomName = uuid.v4();
          randomName = '/' + randomName.split('-').join('');
          newNamespace = this.io.of(randomName);
          console.log(newNamespace.name);
          game = new GameLobby(this.io, newNamespace, this, new Config(['mafia', 'villager', 'villager']));
          gameObject = {
            game: game,
            namespace: newNamespace
          };
          this.gamesArray.push(gameObject);
          _results.push(console.log('made new game'));
        }
      }
      return _results;
    };

    QueueManager.prototype.addToQueue = function(game) {
      return this.gamesArray.push(game);
    };

    return QueueManager;

  })();

  exports.QueueManager = QueueManager;

}).call(this);

/*
//@ sourceMappingURL=QueueManager.map
*/
