// Generated by CoffeeScript 1.6.3
(function() {
  var DefaultRole,
    __hasProp = {}.hasOwnProperty;

  DefaultRole = (function() {
    function DefaultRole() {}

    DefaultRole.prototype.actions = ['visit', 'death'];

    DefaultRole.prototype.initializeState = function(currentRoleState) {
      currentRoleState.roleID = this.roleID;
      currentRoleState.allegiance = this.allegiance;
      currentRoleState.dead = false;
      currentRoleState.causeOfDeath = void 0;
      currentRoleState.killer = void 0;
      currentRoleState.vest = 0;
      currentRoleState.visited = {
        1: []
      };
      return currentRoleState.visitors = {
        1: []
      };
    };

    DefaultRole.prototype.publicStateInitialize = function(playerObject, gameEngine, config) {
      var newState, player, playerobject, _ref;
      newState = {};
      newState.name = playerObject.currentState.name;
      newState.role = playerObject.currentState.roleID;
      newState.publicPlayers = {};
      _ref = gameEngine.getGameState().players;
      for (player in _ref) {
        if (!__hasProp.call(_ref, player)) continue;
        playerobject = _ref[player];
        newState.publicPlayers[player] = {};
      }
      newState.reports = {};
      newState.legalActions = [];
      newState.chats = {
        "public": true
      };
      newState.turn = 1;
      return newState;
    };

    DefaultRole.prototype.death = {
      priority: 5,
      func: function(args, currentState, gameEngine) {
        var gameState;
        gameState = gameEngine.getGameState();
        currentState.dead = true;
        currentState.causeOfDeath = args.how;
        currentState.killer = args.who;
        gameState.grave.push(currentState.name);
        return false;
      }
    };

    DefaultRole.prototype.visit = {
      priority: 1,
      func: function(args, currentState, gameEngine) {
        var playerObject;
        playerObject = gameEngine.getPlayerObject(currentState.name);
        playerObject.addToVisitors(args.who);
        return true;
      }
    };

    return DefaultRole;

  })();

  exports.DefaultRole = DefaultRole;

}).call(this);

/*
//@ sourceMappingURL=default.map
*/
