// Generated by CoffeeScript 1.6.3
(function() {
  exports.villager = require('./villager').villager;

  exports.mafia = require('./mafia').mafia;

}).call(this);

/*
//@ sourceMappingURL=index.map
*/
