// Generated by CoffeeScript 1.6.3
(function() {
  var Config, GameEngine, i, log, mafia, mafia1, mafia2, mafiaInfo, newgame, playerSet, playerSet1, playerSet2, players, time1, time2, villager, villager1, villager2, villagerInfo, _i, _j, _k, _l, _len, _len1, _len2, _len3, _m, _n;

  log = function() {
    var thelog, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = arguments.length; _i < _len; _i++) {
      thelog = arguments[_i];
      _results.push(console.log(thelog));
    }
    return _results;
  };

  GameEngine = require('./GameEngine').GameEngine;

  Config = require('./config').Config;

  villagerInfo = function(name) {
    this.name = name;
    return this.role = 'villager';
  };

  mafiaInfo = function(name) {
    this.name = name;
    return this.role = 'mafia';
  };

  time1 = new Date();

  for (i = _i = 1; _i < 2000; i = ++_i) {
    newgame = new GameEngine(io, ioNamespace, new Config);
    players = [];
    for (i = _j = 1; _j < 10; i = ++_j) {
      players.push([Math.random().toString(36).substring(7), Math.random().toString(36).substring(7)]);
    }
    for (_k = 0, _len = players.length; _k < _len; _k++) {
      playerSet = players[_k];
      villager = playerSet[0];
      mafia = playerSet[1];
      newgame.addPlayer(new villagerInfo(villager));
      newgame.addPlayer(new mafiaInfo(mafia));
    }
    for (_l = 0, _len1 = players.length; _l < _len1; _l++) {
      playerSet1 = players[_l];
      villager1 = playerSet1[0];
      mafia1 = playerSet1[1];
      for (_m = 0, _len2 = players.length; _m < _len2; _m++) {
        playerSet2 = players[_m];
        villager2 = playerSet2[0];
        mafia2 = playerSet2[1];
        newgame.getCommandManager().preValidateActive('active', {
          targetname: villager2
        }, mafia1, false);
      }
    }
    for (_n = 0, _len3 = players.length; _n < _len3; _n++) {
      playerSet1 = players[_n];
      newgame.nextTurn();
      villager1 = playerSet1[0];
      mafia1 = playerSet1[1];
      newgame.getCommandManager().preValidateActive('active', {
        targetname: villager1
      }, mafia1, false);
    }
    newgame.getCommandManager().callActives();
  }

  time2 = new Date();

  log('time', time2 - time1, 'time');

}).call(this);

/*
//@ sourceMappingURL=gametest.map
*/
