// Generated by CoffeeScript 1.6.3
(function() {
  var UserManager, randomName, uuid;

  randomName = require('sillyname');

  uuid = require('node-uuid');

  UserManager = (function() {
    function UserManager() {
      this.userMap = {};
    }

    UserManager.prototype.setUser = function(socket, playerInfo) {
      var timeAdded, user;
      if (!playerInfo.name) {
        playerInfo.name = randomName();
        playerInfo.name = playerInfo.name;
      }
      timeAdded = new Date();
      user = {
        name: playerInfo.name,
        timeAdded: timeAdded,
        game: void 0
      };
      socket.playerName = playerInfo.name;
      this.userMap[socket.id] = user;
      return socket.emit('playerFound', user);
    };

    UserManager.prototype.getUser = function(socketID) {
      return this.userMap[socketID];
    };

    return UserManager;

  })();

  exports.UserManager = new UserManager();

}).call(this);

/*
//@ sourceMappingURL=UserManager.map
*/
